branches:
  only:
  - master
language: objective-c
osx_image: xcode8.1
env:
  matrix:
  - OS='10.1' name='iPhone 6'
  global:
  - APP_NAME="Udarealm"
  - 'DEVELOPER_NAME="iPhone Distribution: Nanjing Viroyal Network Technology Co.,
    Ltd. (N7F69UBB9A)"'
  - PROFILE_NAME="Udarealm_Ad_Hoc"
  - secure: fp6+OWfqSq9fRCaJ1XqZtAVjF5aJgxFxOyDIZc4WA2J8EfufzWAQvTYwKuCZv7ZQGM6ubbOsnq5XS5Udm8WuAppJ3Yis+h+gonPltXPH/SdSoAkwjHw+9tyLKY+6t8N9oMueTwN97tMQb+PrdX02EVdwwhZDk7HyrosLASJeiNFeiYFbyeg+jCHF0gsuUzvbtuQyTKuXre6fAsjbF4iMn1TgR1b0YGYsKthMn2FkDDaLpRwFXGj0V0a6JVlBtMneZQBGCVXL2x2Gvafd9VvR1s3rNp4lodWmx4GBEKFShesmJqhwFVqto5gwTRzfFRbxFaFKMeQfFceiYGSLMMq7/eJV1oKOiT8ggHi3Yl/UqQ3MbQSobNs8VQ01rQJ4YpxGaM7YaDnNp3I/GJkHWp4PILeCUsyFBpYNN2W8WfztZphdwj0x3cKefKUJmMpPc7QuKjZ4kIcfS+46ffLdOQKcNsqcziENUaJwcsuv15XMcYtvR6Ad/BwqBhSMfkh8ICwnFXWJWpVIwmhLr5ym0DAmkI8jxtla8sMxsyVpRg8CaAViFC789Hr8QFCM7P3U+t7Ry5y6c4dyPHUX/PkKZS4eW6Ch5RmtmtNmlyjAPswA4ZjEEK89IH62ib+vfCtr4PYzL3pDFv9pYSz7I82jVhN+cAzNdd/wXwJa/NuTk1CdtY4=
before_install:
- brew update
- gem install cocoapods
- gem install fir-cli
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/$PROFILE_NAME.mobileprovision.enc
  -d -a -out scripts/profile/$PROFILE_NAME.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- ./scripts/add-key.sh
- pod install --verbose --no-repo-update
script:
- xcodebuild -workspace $APP_NAME.xcworkspace -scheme Today    -sdk iphoneos -configuration
  Release ONLY_ACTIVE_ARCH=NO OBJROOT=$PWD/build SYMROOT=$PWD/build CODE_SIGN_IDENTITY="$DEVELOPER_NAME"
- xcodebuild -workspace $APP_NAME.xcworkspace -scheme $APP_NAME -sdk iphoneos -configuration
  Release ONLY_ACTIVE_ARCH=NO OBJROOT=$PWD/build SYMROOT=$PWD/build CODE_SIGN_IDENTITY="$DEVELOPER_NAME"
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
